### ISSUE TITLE
Docs typo 2

### ISSUE THREAD

**Issue by codenamejason** [sablier-labs/v2-docs#107]
Link for reference: https://docs.sablier.com/contracts/v2/guides/local-environment

In the `LockupLinearStreamCreatorTest.t.sol` file it shows on line 40 -->
```solidity
creator.DAI().approve({ spender: address(creator), amount: 1337e18 });
```

This test fails with the following error: `Compiler run failed: Error (4974): Named argument "amount" does not match function declaration.`

I updated it to the following to pass the test:
```solidity
creator.DAI().approve(address(creator), 1337e18);
```

**Comment by PaulRBerg** [comment]
Hi @codenamejason, thanks for taking the time to report this.

This seems like a dependency issue, i.e., the implementation of ERC-20 you are using has the `amount` parameter named differently. Make sure that you're using the latest versions of the submodules by running this [`reinit`](https://twitter.com/PaulRBerg/status/1629425771457531905) function.

Or maybe you are intentionally using a different ERC-20 implementation? In this case, you just have to rename `amount` to something else.

At any rate, see what [named function parameters](https://twitter.com/PaulRBerg/status/1574071928544976896) are.
