### ISSUE TITLE
Update docs for 2.1 version of the contracts

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-docs#113]
Ref: 
- core [changelog](https://github.com/sablier-labs/v2-core/blob/ba827e19f52c905fd5d5478d0b7dda10c3ef2800/CHANGELOG.md#110---2023-10-19)
- periphery [changelog](https://github.com/sablier-labs/v2-periphery/blob/d3b07e5dbcf78d4439ff5623856334592063d56b/CHANGELOG.md#110---2023-10-19)

**Comment by PaulRBerg** [comment]
@andreivladbrg it would very helpful if you could provide a little more detail about what this task entails beyond just linking to the changelogs.

e.g.

- [ ] Document batch
- [ ] Remove proxy architecture

**Comment by PaulRBerg** [comment]
Note: once this task is finished, this PR should be merged:

https://github.com/sablier-labs/examples/pull/20
