### ISSUE TITLE
Add one more page for older deployment addresses

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-docs#114]
The idea is to have the standard deployments page(`https://docs.sablier.com/contracts/v2/deployments`) for 2.1 contracts and then we should add a note with a hyperlink that points to the old (2.0) deployments page`https://docs.sablier.com/contracts/v2/deployments/old`

**Comment by andreivladbrg** [comment]
I realized that there is one more option to fix this, and that is to make the deployment addresses section extendable:

![image](https://github.com/sablier-labs/v2-docs/assets/99738872/f9dc8850-5ccc-41ff-981b-273ac4b5f757)

And there you will have:
- Deployment Addresses 
   -  v2.1
   - v2.0
   - v1

I discussed this with @PaulRBerg, and we consider the `https://docs.sablier.com/contracts/v2/deployments/old` version to be better.

@gavriliumircea  @razgraf wdyt?

**Comment by PaulRBerg** [comment]
> hyperlink that points to the old (2.0) deployments page `https://docs.sablier.com/contracts/v2/deployments/old`

This is directionally correct but the hyperlink should use `v2.0` instead of `old` because we will also ship V2.2 someday

**Comment by gavriliumircea** [comment]
I am fine with using separate hyperlinks.

**Comment by PaulRBerg** [comment]
Closing - this is how we resolved this:

- The [default deployments page](https://docs.sablier.com/contracts/v2/deployments) points to the latest protocol version (V2.1 at the time of posting this comment)
- There's a new section in the sidebar called "Older Deployments", which contains pages for other deployments (e.g., V2.0)

<img width="300" alt="SCR-20231230-luzq" src="https://github.com/sablier-labs/v2-docs/assets/8782666/dc2f359a-2f5b-4fdf-90f7-7c4049ed7d31">
