### ISSUE TITLE
Clarify when gas fees are paid

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-docs#116]
Over time, many users have asked us when gas fees are paid. We should clarify in the docs that gas is paid only at deposit and withdrawal time.

**Comment by smol-ninja** [comment]
In my PR, I have added the answer to those questions in the form of QnA on the Fees page but I don't like it too much as the page is about protocol-related fees. So I have two points that I would like to discuss:
1. Should we have a whole section about the gas fee on the Fees page? And then we go on saying that "There are three types of fees in Sablier".
2. Should we have a separate page on Gas fees? I don't think It belongs to the same category as Protocol fees and broker fees. 

Any other thought?

**Comment by PaulRBerg** [comment]
Sorry, I've merged your PR before seeing your questions here.

1. I've simply renamed the "Q&A" section to "Gas Fees" [here](https://docs.sablier.com/concepts/protocol/fees)
2. Not worth it to have a separate page just for this
