### ISSUE TITLE
Mermaid.js diagrams

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-docs#13]
- [x] Access Control
- [x] Lockup Linear
- [x] Lockup Dynamic (emphasis on segments)
- [x] Hooks
- [x] Reference Overview (show how all contracts interact with one another)
- [x] Status Transitions

**Comment by PaulRBerg** [comment]
@maxdesalle - this GitHub issue is connected to my recent Slack message.

> Produce two Mermaid.js diagrams that show how streams are stored in the Lockup Linear and Lockup Dynamic contracts.
>
> We are taking for granted that these contracts are singletons, but someone unfamiliar with Sablier might not find it so obvious that all LL/ LD streams are stored in a single, monolith contract.
>
> Something like:
> - Show Lockup Linear/ Dnyamic in a big node
> - Stack multiple streams (5-10) in a vertical list of nodes (comparatively smaller to the contract node)
> - Connect the streams to the contract node using arrows
> - Add annotations that reference some key properties, e.g. deposit amount, start time, end time, etc.
> - Drawing some inspiration from [Uniswap V4's diagrams](https://sablier.slack.com/archives/C04SFH5QMAR/p1688237516281539) would be helpful (structural, not aesthetic inspiration)

**Comment by maxdesalle** [comment]
Would something like this fit @PaulRBerg? Didn't exactly follow your guidelines. Basically tried to show the "deconstruction" of the a stream from the contract to its key properties. Let me know what you think about it!

<img width="552" alt="CleanShot 2023-07-10 at 22 15 22@2x" src="https://github.com/sablier-labs/v2-docs/assets/70470326/3c5cfbad-293c-411e-a0e3-4493d064c800">

**Comment by PaulRBerg** [comment]
That's a good start, @maxdesalle!

Feedback:

- It would be nice if we could place the word "contract" underneath "Lockup Linear", not next to it
- "End time" instead of "stop time"
- "Deposit amount" instead of "Deposit time"
- Differentiate the node shapes
   - For streams: [cylindrical shape](https://mermaid.js.org/syntax/flowchart.html#a-node-in-a-cylindrical-shape)
   - For properties (e.g. "start time"): [assymetric shape](https://mermaid.js.org/syntax/flowchart.html#a-node-in-an-asymmetric-shape) or [stadium shape](https://mermaid.js.org/syntax/flowchart.html#a-stadium-shaped-node)

**Comment by maxdesalle** [comment]
<img width="512" alt="CleanShot 2023-07-11 at 17 54 23@2x" src="https://github.com/sablier-labs/v2-docs/assets/70470326/33c45101-c801-46df-aba8-2c33f2ec506f">
This better @PaulRBerg? If this fits, I will create another version with additional details for Lockup Dynamic.

**Comment by PaulRBerg** [comment]
Looks great, @maxdesalle!
