### ISSUE TITLE
Set-up Algolia search

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-docs#23]
Once we publish the docs website, we will be able to index it by applying here:

https://docsearch.algolia.com/apply/

**Comment by PaulRBerg** [comment]
Just applied now:

> Your DocSearch application request have already been received and is being processed by our team. You will hear from us soon!

**Comment by PaulRBerg** [comment]
@maxdesalle - Algolia is still not working. Can you take a look, please?

<img width="300" alt="SCR-20230712-mffy" src="https://github.com/sablier-labs/v2-docs/assets/8782666/dbe8207a-8ab1-43cb-b252-1c57bfd72244">

**Comment by maxdesalle** [comment]
Fixed in [7a6e60b](https://github.com/sablier-labs/v2-docs/commit/7a6e60baaa84e20e30b3a345b54e79f8f0cabf57)! Turns out the problem was that the email I received from Algolia contained the wrong API key, had to go find the actual one on their interface 🤦‍♂️

**Comment by PaulRBerg** [comment]
WORKS! Thanks, Max.

Quick q: do we need to constantly ping Algolia whenever we make updates, or do they automatically re-index the website?

might be worth reaching out to them to confirm

**Comment by maxdesalle** [comment]
It crawls our documentation website every week on Monday, but we can trigger it manually too when needed.

**Comment by PaulRBerg** [comment]
perfect
