### ISSUE TITLE
Add pointing arrow icon next to hyperlinks

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-docs#34]
It would be nice to add a pointing arrow next to hyperlinks, which don't have any special formatting at the moment besides being colored in orange.

I like how [Balancer](https://docs.balancer.fi/reference/contracts/deployment-addresses/arbitrum.html) renders hyperlinks:

<img width="906" alt="SCR-20230706-qxkz" src="https://github.com/sablier-labs/v2-docs/assets/8782666/b5c994ca-a725-496b-a65f-5bf478bf993b">

**Comment by PaulRBerg** [comment]
Thought, on seconds thoughts, what I don't like about the current formatting is not so much that there is no pointing arrow - it's more about being a lot of orange (it looks flashy):

<img width="364" alt="SCR-20230706-qyod" src="https://github.com/sablier-labs/v2-docs/assets/8782666/1de12500-a173-4bd9-b8f1-884cd7ef2f5f">

Thus, I'd be on board with any other solution that reduces the amount of orange on screen.

**Comment by razgraf** [comment]
| Blue | Blue |
|--------|--------|
| ![Screenshot 2023-07-07 at 00 30 53](https://github.com/sablier-labs/v2-docs/assets/15740806/3bad2c7b-b4af-4732-95f1-8d2ff10eb836) | ![Screenshot 2023-07-07 at 00 30 36](https://github.com/sablier-labs/v2-docs/assets/15740806/d151da72-1839-4b42-a416-2f82ae20f217) | 

| Yellow | Purple |
|--------|--------|
| ![Screenshot 2023-07-07 at 00 32 33](https://github.com/sablier-labs/v2-docs/assets/15740806/b6e1d260-1b20-4f6e-b510-7b068e19d0df) | ![Screenshot 2023-07-07 at 00 32 56](https://github.com/sablier-labs/v2-docs/assets/15740806/e12a274c-7025-4234-bed4-b6b07e62df1b) |

**Comment by razgraf** [comment]
And .. for the arrow (with some special logic for footnotes), two versions

| Example | Example |
|--------|--------|
| ![Screenshot 2023-07-07 at 01 16 58](https://github.com/sablier-labs/v2-docs/assets/15740806/32c805c9-f72b-4429-bf72-c26d4068ea41) | ![Screenshot 2023-07-07 at 01 15 57](https://github.com/sablier-labs/v2-docs/assets/15740806/66936c3e-34d6-47ae-a1ce-2e4477a8ccf3) |
| ![Screenshot 2023-07-07 at 01 19 08](https://github.com/sablier-labs/v2-docs/assets/15740806/aad896a2-cac4-4dd3-a726-54e4d3dcdb46) | ![Screenshot 2023-07-07 at 01 14 28](https://github.com/sablier-labs/v2-docs/assets/15740806/b2f960f0-bd88-4ebb-99c0-31d6c95bb6b4)

**Comment by PaulRBerg** [comment]
Oh .. now there's too much blue 😆

Dunno, I'll let you decide, but I'd keep orange.

For the arrow I like the 2nd version (at the bottom),

**Comment by razgraf** [comment]
Great! Arrow added, color switch to orange (although it now uses our own value for orange and changes the shade a bit between light and dark mode to account for contrast).
