### ISSUE TITLE
Delete all unused "import React from react" statements

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-docs#35]
[Starting with React v17](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html), JSX can be used without importing React. No longer do we have to import React in the global scope, or add it as a dependency:

https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports

**Comment by razgraf** [comment]
There's an eslint plugin preventing this in the current version. It either has to be removed or the rule itself suppressed.

**Comment by PaulRBerg** [comment]
https://stackoverflow.com/a/68315971/3873510

**Comment by PaulRBerg** [comment]
Nevermind, Docusaurus is not compatible with the new JSX transformer:

[ReferenceError: React is not defined](https://app.warp.dev/block/92iiNfLEV1XkQSNtC0ANHc).
