### ISSUE TITLE
Add app/interfaces section

### ISSUE THREAD

**Issue by razgraf** [sablier-labs/v2-docs#50]
Suggestion to add a new section including non-code documentation such as:

- tutorials (linking to youtube) 
- a quick list of app features
- a "branding" section where we link the logo and other resources

**Comment by PaulRBerg** [comment]
Just to clarify - the suggestion is to add this new section in the top-left navbar, right?

<img width="300" alt="SCR-20230708-ptza" src="https://github.com/sablier-labs/v2-docs/assets/8782666/fed74d06-67c4-400b-8b4b-a12fd3c042db">
