### ISSUE TITLE
Improve reference overview diagrams

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-docs#61]
I've been reviewing the diagrams and I think they are a little bit misleading.

For example, the [create a stream](https://docs.sablier.com/contracts/v2/reference/diagrams#create-a-stream) diagram is making me believe that:
1. The Proxy has a `create` function
2. The Proxy Target directly calls the core contract
3. ERC-20 assets will be held in Permit2 contract

All three points from above are incorrect.

<img width="827" alt="image" src="https://github.com/sablier-labs/v2-docs/assets/99738872/7ae04d6f-0e5c-4945-9219-d2ff33c6c11c">

The first two points can be also applied to [sender-withdraws](https://docs.sablier.com/contracts/v2/reference/diagrams#sender-withdraws) diagram:

<img width="903" alt="image" src="https://github.com/sablier-labs/v2-docs/assets/99738872/430f7ea8-2ef5-47d9-befd-a12e1a5b65ef">

As well, I would say that changing the final node for `recipient` would be more appropriate,  with the connecting line indicating something like `ERC20-transfer`.

**Comment by PaulRBerg** [comment]
Agree with your suggestion!
