### ISSUE TITLE
No social media preview

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-docs#64]
The docs website doesn't have any social media preview at the moment:

<img width="300" alt="SCR-20230712-mzcd" src="https://github.com/sablier-labs/v2-docs/assets/8782666/899b9e4a-f70f-4f03-aab1-4a06f94df8c0">

@razgraf could you please add the simple preview that used to be on `sablier.com` before moving to the app + logo preview?

**Comment by razgraf** [comment]
Thank you for taking care of it!
