### ISSUE TITLE
Fix integration template link

### ISSUE THREAD

**Issue by hosseinnedaee** [sablier-labs/v2-docs#73]
In the [configure your local environment](https://docs.sablier.com/contracts/v2/guides/local-environment) the integration template github link is incorrect.
this:
`forge init --template sablier-v2-integration-template`
should be changed to this:
`forge init --template sablier-labs/sablier-v2-integration-template`

**Comment by PaulRBerg** [comment]
Thanks for reporting! This issue was closed by https://github.com/sablier-labs/v2-docs/pull/74
